swagger: "2.0"
info:
  version: "1.0.1"
  # Integrated with OpenSentencingModel data objects
  title: "Outcarcerate"
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: "/v1"
tags:
- name: "attorney"
  description: "Attorney"
- name: "client"
  description: "Client"
- name: "case"
  description: "Case"
- name: "charge"
  description: "Charge"
# Added this new model object as a part of v1.0.1  
- name: "sentence"
  description: "Sentence"
schemes:
- "https"
- "http"
paths:
  /attorney:
    post:
      tags:
      - "attorney"
      summary: "Add a new attorney"
      description: ""
      operationId: "addAttorney"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Attorney"
      responses:
        "405":
          description: "Invalid input"
    get:
      tags:
      - "attorney"
      summary: "Get a list of attorneys"
      description: "Returns a all attorneys"
      operationId: "getAllAttorneys"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/AttorneyResponse"
  /attorney/{attorneyId}:
    get:
      tags:
      - "attorney"
      summary: "Find attorney by ID"
      description: "Returns a single attorney"
      operationId: "getAttorneyById"
      produces:
      - "application/json"
      parameters:
      - name: "attorneyId"
        in: "path"
        description: "ID of attorney to return"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/AttorneyResponse"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Attorney not found"
  /client:
    post:
      tags:
      - "client"
      summary: "Add a new client"
      description: ""
      operationId: "addClient"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Client"
      responses:
        "405":
          description: "Invalid input"
    get:
      tags:
      - "client"
      summary: "Get a list of clients for an attorney"
      description: "Returns all clients of an attorney"
      operationId: "getClients"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/ClientFilter"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ClientResponse"
  /client/{clientId}:
    get:
      tags:
      - "client"
      summary: "Find client by ID"
      description: "Returns a single client"
      operationId: "getClientById"
      produces:
      - "application/json"
      parameters:
      - name: "clientId"
        in: "path"
        description: "ID of client to return"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ClientResponse"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Client not found"
definitions:
  Charge:
    type: "object"
    required:
    - "trial_type"
    - "charge_code"
    - "attempted"
    - "primary"
    - "sentence_type"
    - "minimum_incarceration_months"
    - "maximum_incarceration_months"
    - "probation_term_months"
    - "fine_dollars"
    - "community_service_hours"
    - "alternative_sentence"
    - "suspended_sentence"
    - "disposition_charged_class"
    properties:
      id:
        type: "string"
      rev:
        type: "string"
      trial_type:
        type: "string"
        enum:
          - "Guilty plea"
          - "Trial by judge"
          - "Trial by jury"
      disposition_charged_class:
        type: "string"
      charge_code:
        type: "string"
        enum:
          -	"Administration of Justice"
          -	"Aggravated Assault Police Officer"
          -	"Aggravated Battery Police Officer"
          -	"Aggravated Battery With A Firearm"
          -	"Aggravated Battery"
          -	"Aggravated Discharge Firearm"
          -	"Aggravated DUI"
          -	"Aggravated Fleeing and Eluding"
          -	"Aggravated Identity Theft"
          -	"Aggravated Robbery"
          -	"Antitrust"
          -	"Armed Robbery"
          -	"Armed Violence"
          -	"Arson and Attempt Arson"
          -	"Arson"
          -	"Attempt Armed Robbery"
          -	"Attempt Arson"
          - "Attempt First Degree Murder"
          -	"Attempt Homicide"
          -	"Attempt Sex Crimes"
          -	"Attempt Vehicular Hijacking"
          -	"Battery"
          -	"Bomb Threat"
          -	"Bribery"
          -	"Bribery/Corruption"
          -	"Burglary"
          -	"Burglary/Trespass"
          -	"Child Abduction"
          -	"Child Pornography"
          -	"Commercialized Vice"
          -	"Communicating With Witness"
          -	"Credit Card Cases"
          -	"Criminal Damage to Property"
          -	"Criminal Trespass To Residence"
          -	"Deceptive Practice"
          -	"Disarming Police Officer"
          -	"Dog Fighting"
          -	"Domestic Battery"
          -	"Driving With Suspended Or Revoked License"
          -	"Drug Possession"
          -	"Drug Trafficking"
          -	"DUI"
          -	"Environmental"
          -	"Escape - Failure to Return"
          -	"Extortion/Racketeering"
          - "FALSIFICATION OF ACCOUNTS"
          -	"Failure to Register as a Sex Offender"
          -	"Firearms"
          -	"Food and Drug"
          -	"Forgery"
          -	"Forgery/Counter/Copyright"
          -	"Fraud"
          -	"Fraud/Theft/Embezzlement"
          -	"Fraudulent ID"
          -	"Gambling"
          -	"Gun - Non UUW"
          -	"Gun Running"
          -	"Hate Crimes"
          -	"Home Invasion"
          -	"Homicide"
          -	"Human Trafficking"
          -	"Identity Theft"
          -	"Immigration"
          -	"Impersonating Police Officer"
          -	"Intimidation"
          -	"Invidual Rights"
          -	"Kidnapping"
          -	"Major Accidents"
          -	"Manslaughter"
          -	"Money Laundering"
          -	"Murder"
          -	"Narcotics"
          -	"National Defense"
          -	"Obscenity/Other Sex Offenses"
          -	"Obstructing Justice"
          -	"Official Misconduct"
          -	"Other Offense"
          -	"Other"
          -	"Pandering"
          -	"Perjury"
          -	"Possession Of Burglary Tools"
          -	"Possession of Contraband in Penal Institution"
          -	"Possession of Explosives"
          -	"Possession of Stolen Motor Vehicle"
          -	"Prison Offenses"
          -	"PROMIS Conversion"
          -	"Prostitution"
          -	"Reckless Discharge of Firearm"
          -	"Reckless Homicide"
          -	"Residential Burglary"
          -	"Retail Theft"
          - "REVOKED/SUSPENDED 2ND+ DUI"
          -	"Robbery"
          -	"Sex Crimes"
          - "SEX WITH ANIMAL/<18 PRESENT"
          -	"Sexual Abuse"
          -	"Stalking"
          -	"Stalking/Harassing"
          -	"Tampering"
          -	"Tax"
          -	"Theft by Deception"
          -	"Theft"
          -	"Unlawful Restraint"
          -	"UUW - Unlawful Use of Weapon"
          -	"Vehicular Hijacking"
          -	"Vehicular Invasion"
          -	"Violate Bail Bond"
          - "VIO BAIL BOND/CLASS X CONVIC"
          -	"Violation of Sex Offender Registration"
          -	"Violation Order Of Protection"
      attempted:
        type: "string"
      primary:
        type: "boolean"
      sentence_type:
        type: "string"
        enum:
          - "Prison Only"
          - "Prison and Alternatives"
          - "Probation Only"
          - "Probation and Alternatives"
          - "Fine Ordered/No Restitution"
          - "Restitution Ordered/No Fine"
          - "Both Fine & Restitution Ordered"
          - "Prison"
          - "Supervision" 
          - "Conditional Discharge" 
          - "Probation"
          - "Jail" 
          - "Conversion" 
          - "Cook County Boot Camp"
          - "Probation Terminated Satisfactorily"
          - "Inpatient Mental Health Services"
          - "Probation Terminated Unsatisfactorily" 
          - "Conditional Release"
          - "Probation Terminated Instanter" 
          - "Death"
          - "2nd Chance Probation"
      minimum_incarceration_months:
        type: "integer"
        format: "int64"
      maximum_incarceration_months:
        type: "integer"
        format: "int64"
      probation_term_months:
        type: "integer"
        format: "int64"
      fine_dollars:
        type: "integer"
        format: "int64"
      community_service_hours:
        type: "integer"
        format: "int64"
      alternative_sentence:
        type: "string"
      suspended_sentence:
        type: "boolean"
  Sentence:
    type: "object"
    required:
    - "chargeDisposition"
    - "judge"
    - "phase"
    - "commitmentTerm"
    - "commitmentUnit"
    - "commitmentType"
    properties:
      id:
        type: "string"
      rev:
        type: "string"
      chargeDisposition:
        type: "string"
        enum:
          - "BFW"
          - "Death Suggested-Cause Abated"
          - "Finding Guilty"
          - "FNG"
          - "FNPC"
          - "Nolle Prosecution"
          - "Null"
          - "Plea of Guilty"
          - "SOL"
          - "Verdict-Not Guilty"
          - "Verdict Guilty"
      judge:
        type: "string"
      phase:
        type: "string"
      commitmentTerm:
        type: "integer"
        format: "int64"
      commitmentUnit:
        type: "string"
      commitmentType:
        type: "string"
     
  Case:
    type: "object"
    required:
    - "crime_description"
    - "reasoning_for_charges"
    - "possible_charges"
    - "lengthOfCaseInDays"
    - "ageAtIncident"
    - "incidentCity"
    - "lawEnforcementAgency"
    - "lawEnforcementUnit"
    properties:
      id:
        type: "string"
      rev:
        type: "string"
      client_id:
        type: "string"
      crime_description:
        type: "string"
      reasoning_for_charges:
        type: "string"
      attorney_id:
        type: "string"
      possible_charges:
        type: "array"
        items:
          $ref: "#/definitions/Charge"
      circuit:
        type: "string"
        enum:
          - "DC Circuit"
          - "1st Circuit"
          - "2nd Circuit"
          - "3rd Circuit"
          - "4th Circuit"
          - "5th Circuit"
          - "6th Circuit"
          - "7th Circuit"
          - "8th Circuit"
          - "9th Circuit"
          - "10th Circuit"
          - "11th Circuit"
      incidentCity:
        type: "string"
      state:
        type: "string"
      district:
        type: "string"
      lengthOfCaseInDays:
        type: "integer"
        format: "int64"
      ageAtIncident:
        type: "integer"
        format: "int64"
      lawEnforcementAgency:
        type: "string"
      lawEnforcementUnit:
        type: "string"
  Client:
    type: "object"
    required:
    - "first_name"
    - "last_name"
    - "attorney_id"
    properties:
      id:
        type: "string"
      rev:
        type: "string"
      first_name:
        type: "string"
      last_name:
        type: "string"
      race:
        type: "string"
        enum:
          - White
          - Black
          - Hispanic
          - Other
          - Asian
          - American Indian
          - Biracial
          - White [Hispanic or Latino]
          - White/Black [Hispanic or Latino]
          - Unknown
      gender:
        enum:
          - Female
          - Male
          - Other
          - Unknown
        type: "string"
      prior_felony_convictions:
        type: "integer"
        format: "int64"
      prior_misdemeanor_convictions:
        type: "integer"
        format: "int64"
      criminal_history_category:
        type: "string"
        enum:
          - "Category I"
          - "Category II"
          - "Category III"
          - "Category IV"
          - "Category V"
          - "Category VI"
      type_of_legal_representation:
        type: "string"
        enum:
          - "Self"
          - "Court appointed attorney"
          - "Private attorney"
      married:
        type: "boolean"
      annual_income_dollars:
        type: "integer"
        format: "int64"
      education_level_completed:
        type: "string"
        enum:
          - "Less than high school graduate"
          - "High school graduate or equivalent"
          - "Some college"
          - "College graduate or more"
          - "Unknown"
      immigration_status:
        type: "string"
        enum:
          - "US Citizen"
          - "Non-US Citizen"
      number_of_children_under_18_at_home:
        type: "string"
  Attorney:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "string"
      rev:
        type: "string"
      name:
        type: "string"
      cases:
        type: "array"
        items:
          $ref: "#/definitions/Case"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
  AttorneyResponse:
    type: "object"
    required:
    - "success"
    properties:
      code:
        type: "integer"
        format: "int32"
      success:
        type: "boolean"
      error:
        type: "string"
      warning:
        type: "string"
      attorney:
        type: "array"
        items:
          $ref: "#/definitions/Attorney"
  ClientResponse:
    type: "object"
    required:
    - "success"
    properties:
      code:
        type: "integer"
        format: "int32"
      success:
        type: "boolean"
      error:
        type: "string"
      warning:
        type: "string"
      clients:
        type: "array"
        items:
          $ref: "#/definitions/Client"
  ClientFilter:
    type: "object"
    required:
    - "attorneyId"
    properties:
      attorney_id:
        type: "string"