{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ include "starter-kit.name" . }}
    helm.sh/chart: {{ include "starter-kit.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ .Release.Name }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ include "starter-kit.fullname" . }}
imagePullSecrets:
- name: au-icr-io
- name: de-icr-io
- name: icr-io
- name: jp-icr-io
- name: uk-icr-io
- name: us-icr-io
- name: au-icr-io
- name: de-icr-io
- name: dev-au-icr-io
- name: dev-de-icr-io
- name: dev-icr-io
- name: dev-jp-icr-io
- name: dev-uk-icr-io
- name: dev-us-icr-io
- name: icr-io
- name: jp-icr-io
- name: uk-icr-io
- name: us-icr-io
{{- end }}
