version: "3.7"
services: 
  cfcdb:
    image: couchdb:latest
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password

  initializer:
    image: curlimages/curl
    depends_on:
      - cfcdb
    command: ['sh', '/tmp/attorney_init.sh']
    volumes:
      - ./attorney_init.sh:/tmp/attorney_init.sh
