/*
 * Outcarcerate
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.model.Attorney;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;

/**
 * AttorneyResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2020-08-12T21:38:30.799+02:00")
public class AttorneyResponse   {
  @JsonProperty("code")
  private Integer code = null;

  @JsonProperty("success")
  private Boolean success = null;

  @JsonProperty("error")
  private String error = null;

  @JsonProperty("warning")
  private String warning = null;

  @JsonProperty("attorney")
  private List<Attorney> attorney = null;

  public AttorneyResponse code(Integer code) {
    this.code = code;
    return this;
  }

  /**
   * Get code
   * @return code
   **/
  @JsonProperty("code")
  @ApiModelProperty(value = "")
  public Integer getCode() {
    return code;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

  public AttorneyResponse success(Boolean success) {
    this.success = success;
    return this;
  }

  /**
   * Get success
   * @return success
   **/
  @JsonProperty("success")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public Boolean isSuccess() {
    return success;
  }

  public void setSuccess(Boolean success) {
    this.success = success;
  }

  public AttorneyResponse error(String error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   **/
  @JsonProperty("error")
  @ApiModelProperty(value = "")
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }

  public AttorneyResponse warning(String warning) {
    this.warning = warning;
    return this;
  }

  /**
   * Get warning
   * @return warning
   **/
  @JsonProperty("warning")
  @ApiModelProperty(value = "")
  public String getWarning() {
    return warning;
  }

  public void setWarning(String warning) {
    this.warning = warning;
  }

  public AttorneyResponse attorney(List<Attorney> attorney) {
    this.attorney = attorney;
    return this;
  }

  public AttorneyResponse addAttorneyItem(Attorney attorneyItem) {
    if (this.attorney == null) {
      this.attorney = new ArrayList<Attorney>();
    }
    this.attorney.add(attorneyItem);
    return this;
  }

  /**
   * Get attorney
   * @return attorney
   **/
  @JsonProperty("attorney")
  @ApiModelProperty(value = "")
  public List<Attorney> getAttorney() {
    return attorney;
  }

  public void setAttorney(List<Attorney> attorney) {
    this.attorney = attorney;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttorneyResponse attorneyResponse = (AttorneyResponse) o;
    return Objects.equals(this.code, attorneyResponse.code) &&
        Objects.equals(this.success, attorneyResponse.success) &&
        Objects.equals(this.error, attorneyResponse.error) &&
        Objects.equals(this.warning, attorneyResponse.warning) &&
        Objects.equals(this.attorney, attorneyResponse.attorney);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, success, error, warning, attorney);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttorneyResponse {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    warning: ").append(toIndentedString(warning)).append("\n");
    sb.append("    attorney: ").append(toIndentedString(attorney)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

