/*
 * Outcarcerate
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.model.BiasDetectionResponse;
import io.swagger.model.Discrepancy;
import javax.validation.constraints.*;

/**
 * CaseReport
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2020-10-15T21:00:06.855Z")
public class CaseReport   {
  @JsonProperty("code")
  private Integer code = null;

  @JsonProperty("success")
  private Boolean success = null;

  @JsonProperty("error")
  private String error = null;

  @JsonProperty("bias")
  private BiasDetectionResponse bias = null;

  @JsonProperty("discrepancy")
  private Discrepancy discrepancy = null;

  public CaseReport code(Integer code) {
    this.code = code;
    return this;
  }

  /**
   * Get code
   * @return code
   **/
  @JsonProperty("code")
  @ApiModelProperty(value = "")
  public Integer getCode() {
    return code;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

  public CaseReport success(Boolean success) {
    this.success = success;
    return this;
  }

  /**
   * Get success
   * @return success
   **/
  @JsonProperty("success")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public Boolean isSuccess() {
    return success;
  }

  public void setSuccess(Boolean success) {
    this.success = success;
  }

  public CaseReport error(String error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   **/
  @JsonProperty("error")
  @ApiModelProperty(value = "")
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }

  public CaseReport bias(BiasDetectionResponse bias) {
    this.bias = bias;
    return this;
  }

  /**
   * Get bias
   * @return bias
   **/
  @JsonProperty("bias")
  @ApiModelProperty(value = "")
  public BiasDetectionResponse getBias() {
    return bias;
  }

  public void setBias(BiasDetectionResponse bias) {
    this.bias = bias;
  }

  public CaseReport discrepancy(Discrepancy discrepancy) {
    this.discrepancy = discrepancy;
    return this;
  }

  /**
   * Get discrepancy
   * @return discrepancy
   **/
  @JsonProperty("discrepancy")
  @ApiModelProperty(value = "")
  public Discrepancy getDiscrepancy() {
    return discrepancy;
  }

  public void setDiscrepancy(Discrepancy discrepancy) {
    this.discrepancy = discrepancy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CaseReport caseReport = (CaseReport) o;
    return Objects.equals(this.code, caseReport.code) &&
        Objects.equals(this.success, caseReport.success) &&
        Objects.equals(this.error, caseReport.error) &&
        Objects.equals(this.bias, caseReport.bias) &&
        Objects.equals(this.discrepancy, caseReport.discrepancy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, success, error, bias, discrepancy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CaseReport {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    bias: ").append(toIndentedString(bias)).append("\n");
    sb.append("    discrepancy: ").append(toIndentedString(discrepancy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

