/*
 * Outcarcerate
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;

/**
 * Client
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2020-10-13T17:17:47.836Z")
public class Client   {
  @JsonProperty("_id")
  private String _id = null;

  @JsonProperty("_rev")
  private String _rev = null;
  
  @JsonProperty("attorney_id")
  private String attorneyId = null;

  /**
   * Gets or Sets race
   */
  public enum RaceEnum {
    WHITE("White"),
    
    BLACK("Black"),
    
    HISPANIC("Hispanic"),
    
    OTHER("Other"),
    
    ASIAN("Asian"),
    
    AMERICAN_INDIAN("American Indian"),
    
    BIRACIAL("Biracial"),
    
    WHITE_HISPANIC_OR_LATINO_("White [Hispanic or Latino]"),
    
    WHITE_BLACK_HISPANIC_OR_LATINO_("White/Black [Hispanic or Latino]"),
    
    UNKNOWN("Unknown");

    private String value;

    RaceEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RaceEnum fromValue(String text) {
      for (RaceEnum b : RaceEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("race")
  private RaceEnum race = null;

  /**
   * Gets or Sets gender
   */
  public enum GenderEnum {
    FEMALE("Female"),
    
    MALE("Male"),
    
    OTHER("Other"),
    
    UNKNOWN("Unknown");

    private String value;

    GenderEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static GenderEnum fromValue(String text) {
      for (GenderEnum b : GenderEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("gender")
  private GenderEnum gender = null;

  /**
   * Gets or Sets criminalHistoryCategory
   */
  public enum CriminalHistoryCategoryEnum {
    I("Category I"),
    
    II("Category II"),
    
    III("Category III"),
    
    IV("Category IV"),
    
    V("Category V"),
    
    VI("Category VI");

    private String value;

    CriminalHistoryCategoryEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CriminalHistoryCategoryEnum fromValue(String text) {
      for (CriminalHistoryCategoryEnum b : CriminalHistoryCategoryEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("criminal_history_category")
  private CriminalHistoryCategoryEnum criminalHistoryCategory = null;

  public Client id(String id) {
    this._id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   **/
  @JsonProperty("_id")
  @ApiModelProperty(value = "")
  public String getId() {
    return _id;
  }

  public void setId(String id) {
    this._id = id;
  }

  public Client rev(String rev) {
    this._rev = rev;
    return this;
  }

  /**
   * Get rev
   * @return rev
   **/
  @JsonProperty("_rev")
  @ApiModelProperty(value = "")
  public String getRev() {
    return _rev;
  }

  public void setRev(String rev) {
    this._rev = rev;
  }
  
  public Client attorneyId(String attorneyId) {
	    this.attorneyId = attorneyId;
	    return this;
	  }

	  /**
	   * Get attorneyId
	   * @return attorneyId
	   **/
	  @JsonProperty("attorney_id")
	  @ApiModelProperty(required = true, value = "")
	  @NotNull
	  public String getAttorneyId() {
	    return attorneyId;
	  }

	  public void setAttorneyId(String attorneyId) {
	    this.attorneyId = attorneyId;
	  }

  public Client race(RaceEnum race) {
    this.race = race;
    return this;
  }

  /**
   * Get race
   * @return race
   **/
  @JsonProperty("race")
  @ApiModelProperty(value = "")
  public RaceEnum getRace() {
    return race;
  }

  public void setRace(RaceEnum race) {
    this.race = race;
  }

  public Client gender(GenderEnum gender) {
    this.gender = gender;
    return this;
  }

  /**
   * Get gender
   * @return gender
   **/
  @JsonProperty("gender")
  @ApiModelProperty(value = "")
  public GenderEnum getGender() {
    return gender;
  }

  public void setGender(GenderEnum gender) {
    this.gender = gender;
  }

  public Client criminalHistoryCategory(CriminalHistoryCategoryEnum criminalHistoryCategory) {
    this.criminalHistoryCategory = criminalHistoryCategory;
    return this;
  }

  /**
   * Get criminalHistoryCategory
   * @return criminalHistoryCategory
   **/
  @JsonProperty("criminal_history_category")
  @ApiModelProperty(value = "")
  public CriminalHistoryCategoryEnum getCriminalHistoryCategory() {
    return criminalHistoryCategory;
  }

  public void setCriminalHistoryCategory(CriminalHistoryCategoryEnum criminalHistoryCategory) {
    this.criminalHistoryCategory = criminalHistoryCategory;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Client client = (Client) o;
    return Objects.equals(this._id, client._id) &&
        Objects.equals(this._rev, client._rev) &&
        Objects.equals(this.race, client.race) &&
        Objects.equals(this.gender, client.gender) &&
        Objects.equals(this.criminalHistoryCategory, client.criminalHistoryCategory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_id, _rev, race, gender, criminalHistoryCategory);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Client {\n");
    
    sb.append("    _id: ").append(toIndentedString(_id)).append("\n");
    sb.append("    _rev: ").append(toIndentedString(_rev)).append("\n");
    sb.append("    attorney_id: ").append(toIndentedString(attorneyId)).append("\n");
    sb.append("    race: ").append(toIndentedString(race)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    criminalHistoryCategory: ").append(toIndentedString(criminalHistoryCategory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

