/*
 * Outcarcerate
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.model.Sentence;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;

/**
 * Deviation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2020-10-13T17:17:47.836Z")
public class Deviation   {
  @JsonProperty("_id")
  private String id = null;

  @JsonProperty("_rev")
  private String rev = null;

  @JsonProperty("charge_code")
  private String chargeCode = null;

  @JsonProperty("sentence_deviations")
  private List<Sentence> sentenceDeviations = null;

  public Deviation id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   **/
  @JsonProperty("_id")
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Deviation rev(String rev) {
    this.rev = rev;
    return this;
  }

  /**
   * Get rev
   * @return rev
   **/
  @JsonProperty("_rev")
  @ApiModelProperty(value = "")
  public String getRev() {
    return rev;
  }

  public void setRev(String rev) {
    this.rev = rev;
  }

  public Deviation chargeCode(String chargeCode) {
    this.chargeCode = chargeCode;
    return this;
  }

  /**
   * Get chargeCode
   * @return chargeCode
   **/
  @JsonProperty("charge_code")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public String getChargeCode() {
    return chargeCode;
  }

  public void setChargeCode(String chargeCode) {
    this.chargeCode = chargeCode;
  }

  public Deviation sentenceDeviations(List<Sentence> sentenceDeviations) {
    this.sentenceDeviations = sentenceDeviations;
    return this;
  }

  public Deviation addSentenceDeviationsItem(Sentence sentenceDeviationsItem) {
    if (this.sentenceDeviations == null) {
      this.sentenceDeviations = new ArrayList<Sentence>();
    }
    this.sentenceDeviations.add(sentenceDeviationsItem);
    return this;
  }

  /**
   * Get sentenceDeviations
   * @return sentenceDeviations
   **/
  @JsonProperty("sentence_deviations")
  @ApiModelProperty(value = "")
  public List<Sentence> getSentenceDeviations() {
    return sentenceDeviations;
  }

  public void setSentenceDeviations(List<Sentence> sentenceDeviations) {
    this.sentenceDeviations = sentenceDeviations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Deviation deviation = (Deviation) o;
    return Objects.equals(this.id, deviation.id) &&
        Objects.equals(this.rev, deviation.rev) &&
        Objects.equals(this.chargeCode, deviation.chargeCode) &&
        Objects.equals(this.sentenceDeviations, deviation.sentenceDeviations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, rev, chargeCode, sentenceDeviations);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Deviation {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    rev: ").append(toIndentedString(rev)).append("\n");
    sb.append("    chargeCode: ").append(toIndentedString(chargeCode)).append("\n");
    sb.append("    sentenceDeviations: ").append(toIndentedString(sentenceDeviations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

