/*
 * Outcarcerate
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.model.Charge;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;

/**
 * ModelCase
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2020-10-05T20:11:58.952Z")
public class ModelCase   {
  @JsonProperty("_id")
  private String _id = null;

  @JsonProperty("_rev")
  private String _rev = null;

  @JsonProperty("client_id")
  private String clientId = null;

  @JsonProperty("attorney_id")
  private String attorneyId = null;

  @JsonProperty("possible_charges")
  private List<Charge> possibleCharges = new ArrayList<Charge>();

  public ModelCase id(String id) {
    this._id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   **/
  @JsonProperty("_id")
  @ApiModelProperty(value = "")
  public String getId() {
    return _id;
  }

  public void setId(String id) {
    this._id = id;
  }

  public ModelCase rev(String rev) {
    this._rev = rev;
    return this;
  }

  /**
   * Get rev
   * @return rev
   **/
  @JsonProperty("_rev")
  @ApiModelProperty(value = "")
  public String getRev() {
    return _rev;
  }

  public void setRev(String rev) {
    this._rev = rev;
  }

  public ModelCase clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

  /**
   * Get clientId
   * @return clientId
   **/
  @JsonProperty("client_id")
  @ApiModelProperty(value = "")
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public ModelCase attorneyId(String attorneyId) {
    this.attorneyId = attorneyId;
    return this;
  }

  /**
   * Get attorneyId
   * @return attorneyId
   **/
  @JsonProperty("attorney_id")
  @ApiModelProperty(value = "")
  public String getAttorneyId() {
    return attorneyId;
  }

  public void setAttorneyId(String attorneyId) {
    this.attorneyId = attorneyId;
  }

  public ModelCase possibleCharges(List<Charge> possibleCharges) {
    this.possibleCharges = possibleCharges;
    return this;
  }

  public ModelCase addPossibleChargesItem(Charge possibleChargesItem) {
    this.possibleCharges.add(possibleChargesItem);
    return this;
  }

  /**
   * Get possibleCharges
   * @return possibleCharges
   **/
  @JsonProperty("possible_charges")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public List<Charge> getPossibleCharges() {
    return possibleCharges;
  }

  public void setPossibleCharges(List<Charge> possibleCharges) {
    this.possibleCharges = possibleCharges;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelCase _case = (ModelCase) o;
    return Objects.equals(this._id, _case._id) &&
        Objects.equals(this._rev, _case._rev) &&
        Objects.equals(this.clientId, _case.clientId) &&
        Objects.equals(this.attorneyId, _case.attorneyId) &&
        Objects.equals(this.possibleCharges, _case.possibleCharges);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_id, _rev, clientId, attorneyId, possibleCharges);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelCase {\n");
    
    sb.append("    _id: ").append(toIndentedString(_id)).append("\n");
    sb.append("    _rev: ").append(toIndentedString(_rev)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    attorneyId: ").append(toIndentedString(attorneyId)).append("\n");
    sb.append("    possibleCharges: ").append(toIndentedString(possibleCharges)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

