/*
 * Outcarcerate
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;

/**
 * Sentence
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2020-09-24T20:34:04.774Z")
public class Sentence   {
  @JsonProperty("_id")
  private String id = null;

  @JsonProperty("_rev")
  private String rev = null;

  /**
   * Gets or Sets chargeDisposition
   */
  public enum ChargeDispositionEnum {
    BFW("BFW"),
    
    DEATH_SUGGESTED_CAUSE_ABATED("Death Suggested-Cause Abated"),
    
    FINDING_GUILTY("Finding Guilty"),
    
    FNG("FNG"),
    
    FNPC("FNPC"),
    
    NOLLE_PROSECUTION("Nolle Prosecution"),
    
    NULL("Null"),
    
    PLEA_OF_GUILTY("Plea of Guilty"),
    
    SOL("SOL"),
    
    VERDICT_NOT_GUILTY("Verdict-Not Guilty"),
    
    VERDICT_GUILTY("Verdict Guilty");

    private String value;

    ChargeDispositionEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ChargeDispositionEnum fromValue(String text) {
      for (ChargeDispositionEnum b : ChargeDispositionEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("chargeDisposition")
  private ChargeDispositionEnum chargeDisposition = null;

  @JsonProperty("judge")
  private String judge = null;

  @JsonProperty("phase")
  private String phase = null;

  @JsonProperty("commitmentTerm")
  private Long commitmentTerm = null;

  @JsonProperty("commitmentUnit")
  private String commitmentUnit = null;

  @JsonProperty("commitmentType")
  private String commitmentType = null;

  public Sentence id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   **/
  @JsonProperty("_id")
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Sentence rev(String rev) {
    this.rev = rev;
    return this;
  }

  /**
   * Get rev
   * @return rev
   **/
  @JsonProperty("_rev")
  @ApiModelProperty(value = "")
  public String getRev() {
    return rev;
  }

  public void setRev(String rev) {
    this.rev = rev;
  }

  public Sentence chargeDisposition(ChargeDispositionEnum chargeDisposition) {
    this.chargeDisposition = chargeDisposition;
    return this;
  }

  /**
   * Get chargeDisposition
   * @return chargeDisposition
   **/
  @JsonProperty("chargeDisposition")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public ChargeDispositionEnum getChargeDisposition() {
    return chargeDisposition;
  }

  public void setChargeDisposition(ChargeDispositionEnum chargeDisposition) {
    this.chargeDisposition = chargeDisposition;
  }

  public Sentence judge(String judge) {
    this.judge = judge;
    return this;
  }

  /**
   * Get judge
   * @return judge
   **/
  @JsonProperty("judge")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public String getJudge() {
    return judge;
  }

  public void setJudge(String judge) {
    this.judge = judge;
  }

  public Sentence phase(String phase) {
    this.phase = phase;
    return this;
  }

  /**
   * Get phase
   * @return phase
   **/
  @JsonProperty("phase")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public String getPhase() {
    return phase;
  }

  public void setPhase(String phase) {
    this.phase = phase;
  }

  public Sentence commitmentTerm(Long commitmentTerm) {
    this.commitmentTerm = commitmentTerm;
    return this;
  }

  /**
   * Get commitmentTerm
   * @return commitmentTerm
   **/
  @JsonProperty("commitmentTerm")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public Long getCommitmentTerm() {
    return commitmentTerm;
  }

  public void setCommitmentTerm(Long commitmentTerm) {
    this.commitmentTerm = commitmentTerm;
  }

  public Sentence commitmentUnit(String commitmentUnit) {
    this.commitmentUnit = commitmentUnit;
    return this;
  }

  /**
   * Get commitmentUnit
   * @return commitmentUnit
   **/
  @JsonProperty("commitmentUnit")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public String getCommitmentUnit() {
    return commitmentUnit;
  }

  public void setCommitmentUnit(String commitmentUnit) {
    this.commitmentUnit = commitmentUnit;
  }

  public Sentence commitmentType(String commitmentType) {
    this.commitmentType = commitmentType;
    return this;
  }

  /**
   * Get commitmentType
   * @return commitmentType
   **/
  @JsonProperty("commitmentType")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public String getCommitmentType() {
    return commitmentType;
  }

  public void setCommitmentType(String commitmentType) {
    this.commitmentType = commitmentType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sentence sentence = (Sentence) o;
    return Objects.equals(this.id, sentence.id) &&
        Objects.equals(this.rev, sentence.rev) &&
        Objects.equals(this.chargeDisposition, sentence.chargeDisposition) &&
        Objects.equals(this.judge, sentence.judge) &&
        Objects.equals(this.phase, sentence.phase) &&
        Objects.equals(this.commitmentTerm, sentence.commitmentTerm) &&
        Objects.equals(this.commitmentUnit, sentence.commitmentUnit) &&
        Objects.equals(this.commitmentType, sentence.commitmentType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, rev, chargeDisposition, judge, phase, commitmentTerm, commitmentUnit, commitmentType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sentence {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    rev: ").append(toIndentedString(rev)).append("\n");
    sb.append("    chargeDisposition: ").append(toIndentedString(chargeDisposition)).append("\n");
    sb.append("    judge: ").append(toIndentedString(judge)).append("\n");
    sb.append("    phase: ").append(toIndentedString(phase)).append("\n");
    sb.append("    commitmentTerm: ").append(toIndentedString(commitmentTerm)).append("\n");
    sb.append("    commitmentUnit: ").append(toIndentedString(commitmentUnit)).append("\n");
    sb.append("    commitmentType: ").append(toIndentedString(commitmentType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

