name: Open-Sentencing-Aggregator Build
on: [push]
jobs:
    build-prod:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                  java-version: '11'
                  distribution: 'adopt'
            - run: mvn --batch-mode --update-snapshots -Pprod verify
